stages:
  #  - mavenbuild
  #  - maventest
  - mavendeploy
  - androidbuild
  - androidtest

#maven-build:
#    stage: mavenbuild
#    tags:
#        - RCRunner
#    script:
#        - whoami
#        - sudo bash
#        - mvn -v
#        - cd Backend/PocketMonstersDB/PocketMonstersDB
#        - sudo ls
##        - rm PocketBrawlers-0.0.1-SNAPSHOT.jar
##        - cd ../
#        - mvn package

#maven-test:
#  stage: maventest
#  tags:
#    - RCRunner
#  script:
#    - cd Backend/PocketMonstersDB/PocketMonstersDB
#    - mvn test
#  artifacts:
#    paths:
#      - PocketMonstersDB/PocketMonstersDB/target/*.jar

autoDeploy:
  stage: mavendeploy
  tags:
    - RCRunner
  script:
    - cd Backend/PocketMonstersDB/PocketMonstersDB
    - mvn package
    - sudo ls
    - sudo cd target
    - sudo ls
    - sudo mv target/PocketBrawlers-0.0.2-SNAPSHOT.jar /home/target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/pocket_brawlers/gradlew
  tags:
    - DK
  script:
    - cd Frontend/pocket_brawlers
    - ./gradlew build
  artifacts:
    paths:
      - app/build/outputs/

# android-test:
#   image: gjandres/android-ci:latest
#   stage: androidtest
#   before_script:
#     - export GRADLE_USER_HOME=`pwd`/.gradle
#     - chmod +x ./Frontend/pocket_brawlers/gradlew
#   tags:
#     - DK
#   script:
#     - cd Frontend/pocket_brawlers
#     - ./gradlew test
